timestamps {
	node('node-small') {
		stage('Prepare Run') {
			deleteDir()

			dir('ep-aws-infrastructure') {
				git branch: "${env.EP_AWS_INFRASTRUCTURE_BRANCH}", url: 'git@github.elasticpath.net:DevOps/ep-aws-infrastructure.git'
			}

			dir('docker') {
				git branch: "${env.EXTERNAL_SOLRHOME_BRANCH}", url: 'git@github.elasticpath.net:DevOps/Docker.git'
			}
		}

		stage('Create Instance') {
			sh """
				pushd ep-aws-infrastructure/dev-center/studio/

				./ep-dev-center-studio.sh | tee create.log

				popd
			"""
		}

		stage('Deploy') {
			sh """
				pushd ep-aws-infrastructure/dev-center/studio/

				instance_ip=\$(tail -n 1 create.log)
				ssh_key=/etc/ep/secure/ssh/ep-ec2.pem

				sed -i'' 's|DOCKER_IMAGE_TAG|${env.DOCKER_IMAGE_TAG}|g' docker-compose.yml

				scp -i \${ssh_key} docker-compose.* ec2-user@\${instance_ip}:/ep
				scp -i \${ssh_key} -r ${env.WORKSPACE}/docker/EpImageBuilder/config/external-solrHome ec2-user@\${instance_ip}:/ep

				ssh -i \${ssh_key} ec2-user@\${instance_ip} 'sudo \$(aws ecr get-login --no-include-email --region=us-west-2) && pushd /ep && sudo /usr/local/bin/docker-compose up -d'

				popd
			"""
		}
	}
}
