baseurl: /react-pwa-reference-storefront
exclude: [node_modules, non-distributable]
relative_permalinks: false
github:
  url: https://github.com/
repository: elasticpath/react-pwa-reference-storefront
