// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:019f202b-7d9c-4dc9-be4e-adbf4550fa07",
    "aws_cognito_region": "us-west-2",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "EPConversationalInterface",
            "alias": "$LATEST",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
